### ISSUE TITLE
Plugin resets config with each server restart 

### ISSUE THREAD

**Issue by CorpseKitten** [MelonCode/X-Mas#15]
So when starting the server or reloading configs the file overwrites itself with an empty one making the mod completely unusable

This is what it gets replaced with 

```
# 
# if true - plugin will summon chest with spent resources under tree
core:
  holiday-ends: {}
  plugin-enabled: false
xmas:
  tree-lvl:
    sapling:
      lvlup: {}
    small_tree:
      lvlup: {}
    tree:
      lvlup: {}
    magic_tree: {}
  luck: {}
```
